import { Injectable, OnApplicationBootstrap, Logger } from '@nestjs/common'
import { InjectRepository } from '@nestjs/typeorm'
import { Repository } from 'typeorm'
import { VocabularyWord } from '../vocabulary/vocabulary-word.entity'
import { Document } from '../documents/document.entity'
import { ExamQuestion } from '../exam/exam-question.entity'

@Injectable()
export class SeedService implements OnApplicationBootstrap {
  private readonly logger = new Logger(SeedService.name)

  constructor(
    @InjectRepository(VocabularyWord) private readonly wordRepo: Repository<VocabularyWord>,
    @InjectRepository(Document) private readonly documentRepo: Repository<Document>,
    @InjectRepository(ExamQuestion) private readonly examQuestionRepo: Repository<ExamQuestion>,
  ) {}

  async onApplicationBootstrap() {
    await Promise.all([this.seedVocabulary(), this.seedDocuments(), this.seedExamQuestions()])
  }

  private async seedVocabulary() {
    const count = await this.wordRepo.count()
    if (count > 0) return

    const words: Partial<VocabularyWord>[] = [
      // ─── JLPT N5 (초급) ───
      { word: '人', reading: 'ひと', meaning: '사람', exampleSentence: '彼は親切な人です。', exampleTranslation: '그는 친절한 사람입니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '명사'] },
      { word: '本', reading: 'ほん', meaning: '책', exampleSentence: '本を読みます。', exampleTranslation: '책을 읽습니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '명사'] },
      { word: '水', reading: 'みず', meaning: '물', exampleSentence: '水を飲んでください。', exampleTranslation: '물을 마셔 주세요.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '명사'] },
      { word: '山', reading: 'やま', meaning: '산', exampleSentence: '山が高いです。', exampleTranslation: '산이 높습니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '명사'] },
      { word: '川', reading: 'かわ', meaning: '강', exampleSentence: '川で泳ぎます。', exampleTranslation: '강에서 수영합니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '명사'] },
      { word: '学校', reading: 'がっこう', meaning: '학교', exampleSentence: '学校に行きます。', exampleTranslation: '학교에 갑니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '명사'] },
      { word: '友達', reading: 'ともだち', meaning: '친구', exampleSentence: '友達と遊びます。', exampleTranslation: '친구와 놉니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '명사'] },
      { word: '先生', reading: 'せんせい', meaning: '선생님', exampleSentence: '先生は親切です。', exampleTranslation: '선생님은 친절합니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '명사'] },
      { word: '食べる', reading: 'たべる', meaning: '먹다', exampleSentence: 'ご飯を食べます。', exampleTranslation: '밥을 먹습니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '동사'] },
      { word: '飲む', reading: 'のむ', meaning: '마시다', exampleSentence: 'お茶を飲みます。', exampleTranslation: '차를 마십니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '동사'] },
      { word: '行く', reading: 'いく', meaning: '가다', exampleSentence: '駅に行きます。', exampleTranslation: '역에 갑니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '동사'] },
      { word: '来る', reading: 'くる', meaning: '오다', exampleSentence: '友達が来ます。', exampleTranslation: '친구가 옵니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '동사'] },
      { word: '見る', reading: 'みる', meaning: '보다', exampleSentence: 'テレビを見ます。', exampleTranslation: '텔레비전을 봅니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '동사'] },
      { word: '聞く', reading: 'きく', meaning: '듣다', exampleSentence: '音楽を聞きます。', exampleTranslation: '음악을 듣습니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '동사'] },
      { word: '話す', reading: 'はなす', meaning: '말하다', exampleSentence: '日本語で話します。', exampleTranslation: '일본어로 말합니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '동사'] },
      { word: '大きい', reading: 'おおきい', meaning: '크다', exampleSentence: 'この家は大きいです。', exampleTranslation: '이 집은 큽니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '형용사'] },
      { word: '小さい', reading: 'ちいさい', meaning: '작다', exampleSentence: '小さい犬がいます。', exampleTranslation: '작은 개가 있습니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '형용사'] },
      { word: '新しい', reading: 'あたらしい', meaning: '새롭다', exampleSentence: '新しいカバンを買いました。', exampleTranslation: '새 가방을 샀습니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '형용사'] },
      { word: '古い', reading: 'ふるい', meaning: '오래되다', exampleSentence: 'この建物は古いです。', exampleTranslation: '이 건물은 오래됐습니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '형용사'] },
      { word: '高い', reading: 'たかい', meaning: '높다/비싸다', exampleSentence: 'このレストランは高いです。', exampleTranslation: '이 레스토랑은 비쌉니다.', language: 'ja', level: 'beginner', tags: ['JLPT-N5', '형용사'] },

      // ─── JLPT N4 (초중급) ───
      { word: '結婚', reading: 'けっこん', meaning: '결혼', exampleSentence: '来年、結婚します。', exampleTranslation: '내년에 결혼합니다.', language: 'ja', level: 'elementary', tags: ['JLPT-N4', '명사'] },
      { word: '準備', reading: 'じゅんび', meaning: '준비', exampleSentence: '旅行の準備をします。', exampleTranslation: '여행 준비를 합니다.', language: 'ja', level: 'elementary', tags: ['JLPT-N4', '명사'] },
      { word: '練習', reading: 'れんしゅう', meaning: '연습', exampleSentence: '毎日ピアノを練習します。', exampleTranslation: '매일 피아노를 연습합니다.', language: 'ja', level: 'elementary', tags: ['JLPT-N4', '명사'] },
      { word: '授業', reading: 'じゅぎょう', meaning: '수업', exampleSentence: '授業が終わりました。', exampleTranslation: '수업이 끝났습니다.', language: 'ja', level: 'elementary', tags: ['JLPT-N4', '명사'] },
      { word: '電車', reading: 'でんしゃ', meaning: '전철', exampleSentence: '電車で通勤します。', exampleTranslation: '전철로 통근합니다.', language: 'ja', level: 'elementary', tags: ['JLPT-N4', '명사'] },
      { word: '遅れる', reading: 'おくれる', meaning: '늦다, 지각하다', exampleSentence: '会議に遅れました。', exampleTranslation: '회의에 늦었습니다.', language: 'ja', level: 'elementary', tags: ['JLPT-N4', '동사'] },
      { word: '決める', reading: 'きめる', meaning: '결정하다', exampleSentence: '計画を決めましょう。', exampleTranslation: '계획을 결정합시다.', language: 'ja', level: 'elementary', tags: ['JLPT-N4', '동사'] },
      { word: '集まる', reading: 'あつまる', meaning: '모이다', exampleSentence: '公園に人が集まります。', exampleTranslation: '공원에 사람들이 모입니다.', language: 'ja', level: 'elementary', tags: ['JLPT-N4', '동사'] },
      { word: '返す', reading: 'かえす', meaning: '돌려주다', exampleSentence: '本を返します。', exampleTranslation: '책을 돌려줍니다.', language: 'ja', level: 'elementary', tags: ['JLPT-N4', '동사'] },
      { word: '便利', reading: 'べんり', meaning: '편리하다', exampleSentence: 'このアプリは便利です。', exampleTranslation: '이 앱은 편리합니다.', language: 'ja', level: 'elementary', tags: ['JLPT-N4', '형용사(な)'] },
      { word: '丁寧', reading: 'ていねい', meaning: '정중하다', exampleSentence: '丁寧に説明してください。', exampleTranslation: '정중하게 설명해 주세요.', language: 'ja', level: 'elementary', tags: ['JLPT-N4', '형용사(な)'] },
      { word: '残念', reading: 'ざんねん', meaning: '유감이다, 아쉽다', exampleSentence: '負けて残念です。', exampleTranslation: '져서 아쉽습니다.', language: 'ja', level: 'elementary', tags: ['JLPT-N4', '형용사(な)'] },
      { word: '旅行', reading: 'りょこう', meaning: '여행', exampleSentence: '海外旅行が好きです。', exampleTranslation: '해외여행을 좋아합니다.', language: 'ja', level: 'elementary', tags: ['JLPT-N4', '명사'] },
      { word: '運動', reading: 'うんどう', meaning: '운동', exampleSentence: '毎朝運動します。', exampleTranslation: '매일 아침 운동합니다.', language: 'ja', level: 'elementary', tags: ['JLPT-N4', '명사'] },
      { word: '病院', reading: 'びょういん', meaning: '병원', exampleSentence: '病院に行きます。', exampleTranslation: '병원에 갑니다.', language: 'ja', level: 'elementary', tags: ['JLPT-N4', '명사'] },

      // ─── JLPT N3 (중급) ───
      { word: '予定', reading: 'よてい', meaning: '예정, 계획', exampleSentence: '来週の予定を確認します。', exampleTranslation: '다음 주 예정을 확인합니다.', language: 'ja', level: 'intermediate', tags: ['JLPT-N3', '명사'] },
      { word: '経験', reading: 'けいけん', meaning: '경험', exampleSentence: '海外での経験が役に立ちます。', exampleTranslation: '해외에서의 경험이 도움이 됩니다.', language: 'ja', level: 'intermediate', tags: ['JLPT-N3', '명사'] },
      { word: '関係', reading: 'かんけい', meaning: '관계', exampleSentence: '良い関係を築きましょう。', exampleTranslation: '좋은 관계를 쌓읍시다.', language: 'ja', level: 'intermediate', tags: ['JLPT-N3', '명사'] },
      { word: '方法', reading: 'ほうほう', meaning: '방법', exampleSentence: '別の方法を試してください。', exampleTranslation: '다른 방법을 시도해 보세요.', language: 'ja', level: 'intermediate', tags: ['JLPT-N3', '명사'] },
      { word: '目的', reading: 'もくてき', meaning: '목적', exampleSentence: '勉強の目的は何ですか。', exampleTranslation: '공부의 목적은 무엇입니까?', language: 'ja', level: 'intermediate', tags: ['JLPT-N3', '명사'] },
      { word: '状況', reading: 'じょうきょう', meaning: '상황', exampleSentence: '状況を確認してから決めます。', exampleTranslation: '상황을 확인하고 나서 결정합니다.', language: 'ja', level: 'intermediate', tags: ['JLPT-N3', '명사'] },
      { word: '判断', reading: 'はんだん', meaning: '판단', exampleSentence: '正しい判断をしてください。', exampleTranslation: '올바른 판단을 해 주세요.', language: 'ja', level: 'intermediate', tags: ['JLPT-N3', '명사'] },
      { word: '諦める', reading: 'あきらめる', meaning: '포기하다', exampleSentence: '諦めないでください。', exampleTranslation: '포기하지 마세요.', language: 'ja', level: 'intermediate', tags: ['JLPT-N3', '동사'] },
      { word: '落ち着く', reading: 'おちつく', meaning: '진정하다, 안정되다', exampleSentence: '少し落ち着いてから話しましょう。', exampleTranslation: '조금 진정하고 나서 이야기합시다.', language: 'ja', level: 'intermediate', tags: ['JLPT-N3', '동사'] },
      { word: '比較', reading: 'ひかく', meaning: '비교', exampleSentence: '二つの案を比較します。', exampleTranslation: '두 가지 안을 비교합니다.', language: 'ja', level: 'intermediate', tags: ['JLPT-N3', '명사'] },
      { word: '重要', reading: 'じゅうよう', meaning: '중요하다', exampleSentence: '重要な情報を共有します。', exampleTranslation: '중요한 정보를 공유합니다.', language: 'ja', level: 'intermediate', tags: ['JLPT-N3', '형용사(な)'] },
      { word: '複雑', reading: 'ふくざつ', meaning: '복잡하다', exampleSentence: '問題が複雑で困っています。', exampleTranslation: '문제가 복잡해서 곤란합니다.', language: 'ja', level: 'intermediate', tags: ['JLPT-N3', '형용사(な)'] },
      { word: '当然', reading: 'とうぜん', meaning: '당연하다', exampleSentence: '当然の結果です。', exampleTranslation: '당연한 결과입니다.', language: 'ja', level: 'intermediate', tags: ['JLPT-N3', '형용사(な)/부사'] },
      { word: '発表', reading: 'はっぴょう', meaning: '발표', exampleSentence: '会議で発表します。', exampleTranslation: '회의에서 발표합니다.', language: 'ja', level: 'intermediate', tags: ['JLPT-N3', '명사'] },
      { word: '真剣', reading: 'しんけん', meaning: '진지하다', exampleSentence: '真剣に考えています。', exampleTranslation: '진지하게 생각하고 있습니다.', language: 'ja', level: 'intermediate', tags: ['JLPT-N3', '형용사(な)'] },

      // ─── JLPT N2 (중상급) ───
      { word: '把握', reading: 'はあく', meaning: '파악', exampleSentence: '状況を把握してください。', exampleTranslation: '상황을 파악해 주세요.', language: 'ja', level: 'advanced', tags: ['JLPT-N2', '명사'] },
      { word: '概念', reading: 'がいねん', meaning: '개념', exampleSentence: '基本的な概念を理解します。', exampleTranslation: '기본적인 개념을 이해합니다.', language: 'ja', level: 'advanced', tags: ['JLPT-N2', '명사'] },
      { word: '実施', reading: 'じっし', meaning: '실시', exampleSentence: '新しい政策を実施します。', exampleTranslation: '새로운 정책을 실시합니다.', language: 'ja', level: 'advanced', tags: ['JLPT-N2', '명사'] },
      { word: '批判', reading: 'ひはん', meaning: '비판', exampleSentence: '批判を受け入れることが大切です。', exampleTranslation: '비판을 받아들이는 것이 중요합니다.', language: 'ja', level: 'advanced', tags: ['JLPT-N2', '명사'] },
      { word: '傾向', reading: 'けいこう', meaning: '경향', exampleSentence: '最近この傾向が強まっています。', exampleTranslation: '최근 이 경향이 강해지고 있습니다.', language: 'ja', level: 'advanced', tags: ['JLPT-N2', '명사'] },
      { word: '前提', reading: 'ぜんてい', meaning: '전제', exampleSentence: '前提条件を確認しましょう。', exampleTranslation: '전제 조건을 확인합시다.', language: 'ja', level: 'advanced', tags: ['JLPT-N2', '명사'] },
      { word: '徹底', reading: 'てってい', meaning: '철저', exampleSentence: '徹底的に調べます。', exampleTranslation: '철저하게 조사합니다.', language: 'ja', level: 'advanced', tags: ['JLPT-N2', '명사/형용사(な)'] },
      { word: '妥協', reading: 'だきょう', meaning: '타협', exampleSentence: '品質では妥協しません。', exampleTranslation: '품질에서는 타협하지 않습니다.', language: 'ja', level: 'advanced', tags: ['JLPT-N2', '명사'] },
      { word: '余儀ない', reading: 'よぎない', meaning: '부득이하다', exampleSentence: '中止を余儀なくされました。', exampleTranslation: '중지를 부득이하게 하게 됐습니다.', language: 'ja', level: 'advanced', tags: ['JLPT-N2', '형용사'] },
      { word: '一概に', reading: 'いちがいに', meaning: '일률적으로, 단정적으로', exampleSentence: '一概に悪いとは言えません。', exampleTranslation: '일률적으로 나쁘다고는 말할 수 없습니다.', language: 'ja', level: 'advanced', tags: ['JLPT-N2', '부사'] },

      // ─── JLPT N1 (최고급) ───
      { word: '俯瞰', reading: 'ふかん', meaning: '부감, 조감(높은 곳에서 내려다보다)', exampleSentence: '問題を俯瞰的に見てください。', exampleTranslation: '문제를 부감적으로 보세요.', language: 'ja', level: 'native', tags: ['JLPT-N1', '명사'] },
      { word: '忖度', reading: 'そんたく', meaning: '눈치를 보다, 배려하다', exampleSentence: '忖度せずに意見を言ってください。', exampleTranslation: '눈치 보지 말고 의견을 말해 주세요.', language: 'ja', level: 'native', tags: ['JLPT-N1', '명사'] },
      { word: '脆弱', reading: 'ぜいじゃく', meaning: '취약하다', exampleSentence: 'セキュリティの脆弱性を修正します。', exampleTranslation: '보안 취약점을 수정합니다.', language: 'ja', level: 'native', tags: ['JLPT-N1', '형용사(な)'] },
      { word: '醸成', reading: 'じょうせい', meaning: '조성(분위기 등을 만들다)', exampleSentence: '信頼関係を醸成することが重要です。', exampleTranslation: '신뢰 관계를 조성하는 것이 중요합니다.', language: 'ja', level: 'native', tags: ['JLPT-N1', '명사'] },
      { word: '逆説', reading: 'ぎゃくせつ', meaning: '역설', exampleSentence: '逆説的な真実が隠れています。', exampleTranslation: '역설적인 진실이 숨어 있습니다.', language: 'ja', level: 'native', tags: ['JLPT-N1', '명사'] },
      { word: '瑕疵', reading: 'かし', meaning: '결함, 하자', exampleSentence: '製品に瑕疵が見つかりました。', exampleTranslation: '제품에 결함이 발견됐습니다.', language: 'ja', level: 'native', tags: ['JLPT-N1', '명사'] },
      { word: '恣意的', reading: 'しいてき', meaning: '자의적이다', exampleSentence: '恣意的な解釈は危険です。', exampleTranslation: '자의적인 해석은 위험합니다.', language: 'ja', level: 'native', tags: ['JLPT-N1', '형용사(な)'] },
      { word: '顕在化', reading: 'けんざいか', meaning: '현재화, 가시화', exampleSentence: '潜在的な問題が顕在化しています。', exampleTranslation: '잠재적인 문제가 가시화되고 있습니다.', language: 'ja', level: 'native', tags: ['JLPT-N1', '명사'] },
      { word: '斟酌', reading: 'しんしゃく', meaning: '참작', exampleSentence: '事情を斟酌してください。', exampleTranslation: '사정을 참작해 주세요.', language: 'ja', level: 'native', tags: ['JLPT-N1', '명사'] },
      { word: '闊達', reading: 'かったつ', meaning: '활달하다, 거리낌이 없다', exampleSentence: '闊達な議論を歓迎します。', exampleTranslation: '활달한 토론을 환영합니다.', language: 'ja', level: 'native', tags: ['JLPT-N1', '형용사(な)'] },

      // ─── TOEIC 200 (입문) ───
      { word: 'meeting', reading: null, meaning: '회의', exampleSentence: 'We have a meeting at nine.', exampleTranslation: '우리는 9시에 회의가 있습니다.', language: 'en', level: 'beginner', tags: ['TOEIC-200', '명사'] },
      { word: 'office', reading: null, meaning: '사무실', exampleSentence: 'She works in the office.', exampleTranslation: '그녀는 사무실에서 일합니다.', language: 'en', level: 'beginner', tags: ['TOEIC-200', '명사'] },
      { word: 'schedule', reading: null, meaning: '일정, 스케줄', exampleSentence: 'Please check your schedule.', exampleTranslation: '일정을 확인해 주세요.', language: 'en', level: 'beginner', tags: ['TOEIC-200', '명사'] },
      { word: 'manager', reading: null, meaning: '관리자, 매니저', exampleSentence: 'The manager is in a meeting.', exampleTranslation: '매니저는 회의 중입니다.', language: 'en', level: 'beginner', tags: ['TOEIC-200', '명사'] },
      { word: 'email', reading: null, meaning: '이메일', exampleSentence: 'Please send me an email.', exampleTranslation: '이메일을 보내 주세요.', language: 'en', level: 'beginner', tags: ['TOEIC-200', '명사'] },
      { word: 'report', reading: null, meaning: '보고서', exampleSentence: 'I write a report every week.', exampleTranslation: '저는 매주 보고서를 씁니다.', language: 'en', level: 'beginner', tags: ['TOEIC-200', '명사'] },
      { word: 'team', reading: null, meaning: '팀', exampleSentence: 'Our team works together.', exampleTranslation: '우리 팀은 함께 일합니다.', language: 'en', level: 'beginner', tags: ['TOEIC-200', '명사'] },
      { word: 'budget', reading: null, meaning: '예산', exampleSentence: 'We need a bigger budget.', exampleTranslation: '더 큰 예산이 필요합니다.', language: 'en', level: 'beginner', tags: ['TOEIC-200', '명사'] },
      { word: 'customer', reading: null, meaning: '고객', exampleSentence: 'The customer is always right.', exampleTranslation: '고객은 항상 옳습니다.', language: 'en', level: 'beginner', tags: ['TOEIC-200', '명사'] },
      { word: 'project', reading: null, meaning: '프로젝트', exampleSentence: 'The project starts next Monday.', exampleTranslation: '프로젝트는 다음 월요일에 시작합니다.', language: 'en', level: 'beginner', tags: ['TOEIC-200', '명사'] },

      // ─── TOEIC 400 (초급) ───
      { word: 'invoice', reading: null, meaning: '청구서, 인보이스', exampleSentence: 'Please send the invoice by Friday.', exampleTranslation: '금요일까지 청구서를 보내 주세요.', language: 'en', level: 'elementary', tags: ['TOEIC-400', '명사'] },
      { word: 'shipment', reading: null, meaning: '배송, 선적', exampleSentence: 'The shipment arrived yesterday.', exampleTranslation: '배송이 어제 도착했습니다.', language: 'en', level: 'elementary', tags: ['TOEIC-400', '명사'] },
      { word: 'headquarters', reading: null, meaning: '본사', exampleSentence: 'Our headquarters is in Seoul.', exampleTranslation: '우리 본사는 서울에 있습니다.', language: 'en', level: 'elementary', tags: ['TOEIC-400', '명사'] },
      { word: 'department', reading: null, meaning: '부서', exampleSentence: 'Which department do you work in?', exampleTranslation: '어느 부서에서 일하십니까?', language: 'en', level: 'elementary', tags: ['TOEIC-400', '명사'] },
      { word: 'promotion', reading: null, meaning: '승진; 판촉', exampleSentence: 'She got a promotion last month.', exampleTranslation: '그녀는 지난달에 승진했습니다.', language: 'en', level: 'elementary', tags: ['TOEIC-400', '명사'] },
      { word: 'conference', reading: null, meaning: '회의, 컨퍼런스', exampleSentence: 'The annual conference is in May.', exampleTranslation: '연례 회의는 5월에 있습니다.', language: 'en', level: 'elementary', tags: ['TOEIC-400', '명사'] },
      { word: 'contract', reading: null, meaning: '계약서, 계약', exampleSentence: 'Please sign the contract.', exampleTranslation: '계약서에 서명해 주세요.', language: 'en', level: 'elementary', tags: ['TOEIC-400', '명사'] },
      { word: 'revenue', reading: null, meaning: '수익, 매출', exampleSentence: 'Revenue increased by 20% this year.', exampleTranslation: '올해 수익이 20% 증가했습니다.', language: 'en', level: 'elementary', tags: ['TOEIC-400', '명사'] },
      { word: 'complaint', reading: null, meaning: '불만, 민원', exampleSentence: 'We received a complaint from a client.', exampleTranslation: '고객으로부터 불만이 접수됐습니다.', language: 'en', level: 'elementary', tags: ['TOEIC-400', '명사'] },
      { word: 'inventory', reading: null, meaning: '재고', exampleSentence: 'Check the inventory before ordering.', exampleTranslation: '주문 전에 재고를 확인하세요.', language: 'en', level: 'elementary', tags: ['TOEIC-400', '명사'] },

      // ─── TOEIC 600 (중급) ───
      { word: 'accomplish', reading: null, meaning: '달성하다', exampleSentence: 'She accomplished her goal ahead of schedule.', exampleTranslation: '그녀는 일정보다 앞서 목표를 달성했습니다.', language: 'en', level: 'intermediate', tags: ['TOEIC-600', '동사'] },
      { word: 'acquire', reading: null, meaning: '습득하다, 얻다', exampleSentence: 'He acquired new skills during the training.', exampleTranslation: '그는 교육 중에 새로운 기술을 습득했습니다.', language: 'en', level: 'intermediate', tags: ['TOEIC-600', '동사'] },
      { word: 'allocate', reading: null, meaning: '배분하다', exampleSentence: 'The manager allocated resources to each department.', exampleTranslation: '관리자가 각 부서에 자원을 배분했습니다.', language: 'en', level: 'intermediate', tags: ['TOEIC-600', '동사'] },
      { word: 'collaborate', reading: null, meaning: '협력하다', exampleSentence: 'Our teams collaborate on international projects.', exampleTranslation: '우리 팀은 국제 프로젝트에서 협력합니다.', language: 'en', level: 'intermediate', tags: ['TOEIC-600', '동사'] },
      { word: 'implement', reading: null, meaning: '실행하다, 구현하다', exampleSentence: 'We will implement the new policy next month.', exampleTranslation: '다음 달에 새로운 정책을 실행할 것입니다.', language: 'en', level: 'intermediate', tags: ['TOEIC-600', '동사'] },
      { word: 'negotiate', reading: null, meaning: '협상하다', exampleSentence: 'They negotiated a favorable contract with the supplier.', exampleTranslation: '그들은 공급업체와 유리한 계약을 협상했습니다.', language: 'en', level: 'intermediate', tags: ['TOEIC-600', '동사'] },
      { word: 'efficient', reading: null, meaning: '효율적인', exampleSentence: 'The new process is more efficient than before.', exampleTranslation: '새로운 과정이 이전보다 더 효율적입니다.', language: 'en', level: 'intermediate', tags: ['TOEIC-600', '형용사'] },
      { word: 'productive', reading: null, meaning: '생산적인', exampleSentence: 'We had a very productive meeting this morning.', exampleTranslation: '오늘 아침 매우 생산적인 회의를 했습니다.', language: 'en', level: 'intermediate', tags: ['TOEIC-600', '형용사'] },
      { word: 'strategy', reading: null, meaning: '전략', exampleSentence: 'The company developed a new marketing strategy.', exampleTranslation: '회사는 새로운 마케팅 전략을 개발했습니다.', language: 'en', level: 'intermediate', tags: ['TOEIC-600', '명사'] },
      { word: 'sustainable', reading: null, meaning: '지속 가능한', exampleSentence: 'We need sustainable solutions for the environment.', exampleTranslation: '환경을 위한 지속 가능한 해결책이 필요합니다.', language: 'en', level: 'intermediate', tags: ['TOEIC-600', '형용사'] },

      // ─── TOEIC 800 (상급) ───
      { word: 'procurement', reading: null, meaning: '조달', exampleSentence: 'The procurement process was streamlined.', exampleTranslation: '조달 프로세스가 간소화됐습니다.', language: 'en', level: 'advanced', tags: ['TOEIC-800', '명사'] },
      { word: 'reimbursement', reading: null, meaning: '상환, 환급', exampleSentence: 'Submit your receipts for reimbursement.', exampleTranslation: '환급을 위해 영수증을 제출해 주세요.', language: 'en', level: 'advanced', tags: ['TOEIC-800', '명사'] },
      { word: 'arbitration', reading: null, meaning: '중재', exampleSentence: 'The dispute was resolved through arbitration.', exampleTranslation: '분쟁이 중재를 통해 해결됐습니다.', language: 'en', level: 'advanced', tags: ['TOEIC-800', '명사'] },
      { word: 'expedite', reading: null, meaning: '신속히 처리하다', exampleSentence: 'We need to expedite the delivery process.', exampleTranslation: '배송 절차를 신속히 처리해야 합니다.', language: 'en', level: 'advanced', tags: ['TOEIC-800', '동사'] },
      { word: 'contingency', reading: null, meaning: '비상사태, 만일의 경우', exampleSentence: 'We have a contingency plan in place.', exampleTranslation: '비상 계획이 마련되어 있습니다.', language: 'en', level: 'advanced', tags: ['TOEIC-800', '명사'] },
      { word: 'delineate', reading: null, meaning: '명시하다, 구체적으로 서술하다', exampleSentence: 'Please delineate the project scope clearly.', exampleTranslation: '프로젝트 범위를 명확히 명시해 주세요.', language: 'en', level: 'advanced', tags: ['TOEIC-800', '동사'] },
      { word: 'stipulate', reading: null, meaning: '규정하다, 명시하다', exampleSentence: 'The contract stipulates a 30-day notice period.', exampleTranslation: '계약서는 30일 통보 기간을 규정하고 있습니다.', language: 'en', level: 'advanced', tags: ['TOEIC-800', '동사'] },
      { word: 'leverage', reading: null, meaning: '활용하다; 레버리지', exampleSentence: 'We can leverage our existing network.', exampleTranslation: '기존 네트워크를 활용할 수 있습니다.', language: 'en', level: 'advanced', tags: ['TOEIC-800', '동사'] },
      { word: 'fiscal', reading: null, meaning: '재정의, 회계의', exampleSentence: 'The fiscal year ends in December.', exampleTranslation: '회계연도는 12월에 끝납니다.', language: 'en', level: 'advanced', tags: ['TOEIC-800', '형용사'] },
      { word: 'compliance', reading: null, meaning: '준수, 컴플라이언스', exampleSentence: 'We must ensure compliance with regulations.', exampleTranslation: '규정 준수를 보장해야 합니다.', language: 'en', level: 'advanced', tags: ['TOEIC-800', '명사'] },

      // ─── TOEIC 900 (최고급) ───
      { word: 'circumvent', reading: null, meaning: '우회하다, 피하다', exampleSentence: 'We cannot circumvent the legal requirements.', exampleTranslation: '법적 요건을 우회할 수는 없습니다.', language: 'en', level: 'native', tags: ['TOEIC-900', '동사'] },
      { word: 'commensurate', reading: null, meaning: '상응하는, 비례하는', exampleSentence: 'Salary is commensurate with experience.', exampleTranslation: '급여는 경력에 상응합니다.', language: 'en', level: 'native', tags: ['TOEIC-900', '형용사'] },
      { word: 'ameliorate', reading: null, meaning: '개선하다, 완화하다', exampleSentence: 'Steps were taken to ameliorate the situation.', exampleTranslation: '상황을 개선하기 위한 조치가 취해졌습니다.', language: 'en', level: 'native', tags: ['TOEIC-900', '동사'] },
      { word: 'exacerbate', reading: null, meaning: '악화시키다', exampleSentence: 'The delay will exacerbate the problem.', exampleTranslation: '지연은 문제를 악화시킬 것입니다.', language: 'en', level: 'native', tags: ['TOEIC-900', '동사'] },
      { word: 'salient', reading: null, meaning: '두드러진, 중요한', exampleSentence: 'Please highlight the salient points.', exampleTranslation: '중요한 사항을 강조해 주세요.', language: 'en', level: 'native', tags: ['TOEIC-900', '형용사'] },
      { word: 'prerogative', reading: null, meaning: '특권, 고유 권한', exampleSentence: 'Final approval is the CEO\'s prerogative.', exampleTranslation: '최종 승인은 CEO의 고유 권한입니다.', language: 'en', level: 'native', tags: ['TOEIC-900', '명사'] },
      { word: 'unequivocal', reading: null, meaning: '명확한, 분명한', exampleSentence: 'The evidence is unequivocal.', exampleTranslation: '증거는 명확합니다.', language: 'en', level: 'native', tags: ['TOEIC-900', '형용사'] },
      { word: 'pursuant to', reading: null, meaning: '~에 따라, ~에 의거하여', exampleSentence: 'Pursuant to your request, I am sending the documents.', exampleTranslation: '귀하의 요청에 따라 서류를 보내드립니다.', language: 'en', level: 'native', tags: ['TOEIC-900', '전치사구'] },
      { word: 'precipitate', reading: null, meaning: '촉발시키다; 성급한', exampleSentence: 'Do not make a precipitate decision.', exampleTranslation: '성급한 결정을 내리지 마세요.', language: 'en', level: 'native', tags: ['TOEIC-900', '동사/형용사'] },
      { word: 'perfunctory', reading: null, meaning: '형식적인, 건성의', exampleSentence: 'He gave a perfunctory reply.', exampleTranslation: '그는 형식적인 답변을 했습니다.', language: 'en', level: 'native', tags: ['TOEIC-900', '형용사'] },
    ]

    await this.wordRepo.save(words)
    this.logger.log(`Seeded ${words.length} vocabulary words`)
  }

  private async seedDocuments() {
    const count = await this.documentRepo.count()
    if (count > 0) return

    const documents: Partial<Document>[] = [
      {
        title: 'My Daily Routine',
        content: `I wake up at 7 o'clock every morning. First, I wash my face and brush my teeth. Then, I eat breakfast. I usually have toast and coffee. After breakfast, I go to work by train. At work, I sit at my desk and check my emails. I have lunch at noon with my colleagues. We usually go to a nearby restaurant. In the afternoon, I attend meetings and work on reports. I finish work at 6 o'clock. In the evening, I come home and cook dinner. After dinner, I watch TV or read a book. I go to bed at 10 o'clock.`,
        language: 'en', level: 'beginner', estimatedReadingMinutes: 2, tags: ['일상', '루틴'],
      },
      {
        title: 'The Benefits of Learning a New Language',
        content: `Learning a new language offers numerous advantages that extend far beyond simple communication. Research has consistently shown that bilingual individuals demonstrate enhanced cognitive flexibility, improved problem-solving abilities, and greater mental resilience as they age. The process of acquiring a second language forces the brain to constantly switch between linguistic systems, which strengthens executive function and attention control.\n\nFurthermore, language learning provides unique cultural insights, enabling learners to understand diverse perspectives and build meaningful connections across cultural boundaries. Many professionals report that their language skills opened doors to international career opportunities that would otherwise have been inaccessible. In our increasingly globalized economy, multilingual employees are often considered valuable assets by employers.\n\nBeyond career benefits, speaking another language allows travelers to experience foreign cultures more authentically, moving beyond tourist attractions to genuine interactions with local communities. Whether your motivation is professional advancement, cultural exploration, or cognitive enhancement, the investment of time and effort in language learning consistently yields significant rewards.`,
        language: 'en', level: 'intermediate', estimatedReadingMinutes: 4, tags: ['교육', '언어학습'],
      },
      {
        title: '自己紹介',
        content: `はじめまして。私の名前は田中さくらです。東京に住んでいます。大学で英語を勉強しています。毎日、単語を10個覚えます。週に3回、先生と会話の練習をします。\n\n日本語はむずかしいですが、とても楽しいです。いつか日本に行きたいです。日本の食べ物が好きです。すしとラーメンが特に好きです。\n\n趣味は音楽を聞くことと、映画を見ることです。週末は友達と公園に行きます。どうぞよろしくお願いします。`,
        language: 'ja', level: 'beginner', estimatedReadingMinutes: 2, tags: ['자기소개', '일상'],
      },
      {
        title: '日本の四季',
        content: `日本には美しい四季があります。それぞれの季節が独自の魅力を持っており、人々の生活や文化に深く影響を与えています。\n\n春になると、各地で桜が咲き始め、公園や川沿いを淡いピンク色に彩ります。この時期、多くの人々が家族や友人と一緒に花見を楽しみます。桜の季節は約2週間と短いため、日本人はこの美しい瞬間を大切にします。\n\n夏は気温が高く湿度も上がりますが、海水浴や花火大会、お祭りなど様々なイベントが各地で開催されます。特に夏祭りでは浴衣を着た人々が多く見られ、日本の伝統文化を感じることができます。\n\n秋になると、山々の木々が赤や黄色、オレンジ色に染まる紅葉が見られます。この美しい光景を楽しもうと、多くの観光客が日本各地の名所を訪れます。また、秋は食べ物がおいしい季節としても知られており、新米や栗、きのこなどの旬の食材が楽しめます。\n\n冬は寒さが厳しくなり、北海道や東北地方では大量の雪が降ります。スキーやスノーボードを楽しむ人も多く、温泉地も人気を集めます。また、クリスマスやお正月など、冬には重要な行事が続きます。`,
        language: 'ja', level: 'intermediate', estimatedReadingMinutes: 5, tags: ['문화', '계절', '자연'],
      },
    ]

    await this.documentRepo.save(documents)
    this.logger.log(`Seeded ${documents.length} documents`)
  }

  private async seedExamQuestions() {
    const count = await this.examQuestionRepo.count()
    if (count > 0) return

    const questions: Partial<ExamQuestion>[] = [
      // ═══════════════════════════════════════════
      // JLPT N5 — 10문제
      // ═══════════════════════════════════════════
      { examType: 'jlpt', level: 'N5', category: 'grammar',
        question: '「学校___行きます」の（___）に入る助詞を選んでください。',
        options: ['の', 'を', 'に', 'が'], answer: 2,
        explanation: '방향·목적지를 나타낼 때는 조사 「に」를 사용합니다. 「学校に行きます = 학교에 갑니다」' },
      { examType: 'jlpt', level: 'N5', category: 'vocabulary',
        question: '「水」の読み方はどれですか。',
        options: ['かわ', 'やま', 'みず', 'うみ'], answer: 2,
        explanation: '「水」는 「みず（mizu）」로 읽으며 「물」을 뜻합니다.' },
      { examType: 'jlpt', level: 'N5', category: 'grammar',
        question: '「ご飯___食べます」の（___）に入る助詞はどれですか。',
        options: ['が', 'の', 'を', 'に'], answer: 2,
        explanation: '동작의 대상을 나타낼 때는 조사 「を」를 사용합니다. 「ご飯を食べます = 밥을 먹습니다」' },
      { examType: 'jlpt', level: 'N5', category: 'vocabulary',
        question: '「친구」를 일본어로 하면どれですか。',
        options: ['先生', '学校', '友達', '人'], answer: 2,
        explanation: '「友達（ともだち）」는 「친구」를 뜻합니다.' },
      { examType: 'jlpt', level: 'N5', category: 'grammar',
        question: '「彼___親切です」の（___）に入る助詞はどれですか。',
        options: ['を', 'に', 'が', 'は'], answer: 3,
        explanation: '「は」는 주제를 나타내는 조사입니다. 「彼は親切です = 그는 친절합니다」' },
      { examType: 'jlpt', level: 'N5', category: 'vocabulary',
        question: '「大きい」の意味はどれですか。',
        options: ['작다', '새롭다', '크다', '오래되다'], answer: 2,
        explanation: '「大きい（おおきい）」는 「크다」를 뜻하는 い형용사입니다.' },
      { examType: 'jlpt', level: 'N5', category: 'grammar',
        question: '「音楽___聞きます」の（___）に入る助詞はどれですか。',
        options: ['は', 'が', 'に', 'を'], answer: 3,
        explanation: '동작의 대상(목적어)에는 「を」를 사용합니다. 「音楽を聞く = 음악을 듣다」' },
      { examType: 'jlpt', level: 'N5', category: 'vocabulary',
        question: '「食べる」의 의미는 무엇입니까？',
        options: ['가다', '마시다', '먹다', '보다'], answer: 2,
        explanation: '「食べる（たべる）」는 「먹다」를 뜻하는 동사입니다.' },
      { examType: 'jlpt', level: 'N5', category: 'grammar',
        question: '「この家___大きいです」の（___）に入る助詞はどれですか。',
        options: ['が', 'に', 'を', 'で'], answer: 0,
        explanation: '주어를 강조하거나 서술할 때 「が」를 사용합니다. 「この家が大きいです = 이 집이 큽니다」' },
      { examType: 'jlpt', level: 'N5', category: 'vocabulary',
        question: '「선생님」을 일본어로 하면どれですか。',
        options: ['学校', '先生', '友達', '人'], answer: 1,
        explanation: '「先生（せんせい）」는 「선생님」을 뜻합니다.' },

      // ═══════════════════════════════════════════
      // JLPT N4 — 10문제
      // ═══════════════════════════════════════════
      { examType: 'jlpt', level: 'N4', category: 'grammar',
        question: '「もっと練習し___ければなりません」の（___）に入る言葉はどれですか。',
        options: ['な', 'な', 'て', 'に'], answer: 0,
        explanation: '「〜なければなりません = 〜해야 합니다」は 동사 부정형 어근 + 「なければなりません」형태입니다.' },
      { examType: 'jlpt', level: 'N4', category: 'grammar',
        question: '「一度やって___ください」の（___）に入る言葉はどれですか。（의미: 한번 해 보세요）',
        options: ['みて', 'おいて', 'しまって', 'いて'], answer: 0,
        explanation: '「〜てみる」는 「시험 삼아 〜해 보다」를 뜻합니다. 「やってみてください = 해 보세요」' },
      { examType: 'jlpt', level: 'N4', category: 'vocabulary',
        question: '「準備」の意味はどれですか。',
        options: ['연습', '준비', '결혼', '여행'], answer: 1,
        explanation: '「準備（じゅんび）」는 「준비」를 뜻합니다.' },
      { examType: 'jlpt', level: 'N4', category: 'grammar',
        question: '「授業が終わる___で待ってください」の（___）に入る言葉はどれですか。',
        options: ['まで', 'から', 'ために', 'ように'], answer: 0,
        explanation: '「〜まで = 〜까지」는 시간이나 장소의 범위를 나타냅니다. 「終わるまで = 끝날 때까지」' },
      { examType: 'jlpt', level: 'N4', category: 'vocabulary',
        question: '「便利」はどんな品詞ですか。',
        options: ['い형용사', 'な형용사', '동사', '명사만'], answer: 1,
        explanation: '「便利（べんり）」는 な형용사입니다. 「便利な + 명사」 또는 「便利です」로 사용합니다.' },
      { examType: 'jlpt', level: 'N4', category: 'grammar',
        question: '「遅れ___ように、早く出発します」の（___）に入る言葉はどれですか。',
        options: ['ない', 'ないで', 'なく', 'なかった'], answer: 0,
        explanation: '「〜ないように = 〜하지 않도록」は 동사 ない형 + 「ように」입니다.' },
      { examType: 'jlpt', level: 'N4', category: 'vocabulary',
        question: '「残念」의 의미로 올바른 것은？',
        options: ['기쁘다', '편리하다', '유감이다', '정중하다'], answer: 2,
        explanation: '「残念（ざんねん）」는 「유감이다, 아쉽다」를 뜻하는 な형용사입니다.' },
      { examType: 'jlpt', level: 'N4', category: 'grammar',
        question: '「友達に手紙を書いて___」の（___）に入る言葉はどれですか。（의미: 친구에게 편지를 써 놓다）',
        options: ['おきます', 'います', 'あります', 'みます'], answer: 0,
        explanation: '「〜ておく = 미리 〜해 두다」는 준비나 대비를 나타냅니다.' },
      { examType: 'jlpt', level: 'N4', category: 'grammar',
        question: '「旅行する___に、パスポートが必要です」の（___）に入る言葉はどれですか。',
        options: ['ため', 'こと', 'もの', 'よう'], answer: 0,
        explanation: '「〜ために = 〜하기 위해」는 목적을 나타냅니다. 「旅行するために = 여행하기 위해」' },
      { examType: 'jlpt', level: 'N4', category: 'vocabulary',
        question: '「決める」의 의미는？',
        options: ['모이다', '돌려주다', '결정하다', '늦다'], answer: 2,
        explanation: '「決める（きめる）」는 「결정하다」를 뜻하는 타동사입니다.' },

      // ═══════════════════════════════════════════
      // JLPT N3 — 10문제
      // ═══════════════════════════════════════════
      { examType: 'jlpt', level: 'N3', category: 'grammar',
        question: '「雨だった___、試合は行われました」の（___）に入る表現はどれですか。',
        options: ['にもかかわらず', 'ために', 'おかげで', 'せいで'], answer: 0,
        explanation: '「〜にもかかわらず = 〜임에도 불구하고」는 역접을 나타냅니다.' },
      { examType: 'jlpt', level: 'N3', category: 'grammar',
        question: '「地域___気候が違います」の（___）に入る言葉はどれですか。',
        options: ['について', 'によって', 'に対して', 'において'], answer: 1,
        explanation: '「〜によって = 〜에 따라」는 원인이나 수단을 나타냅니다. 「地域によって = 지역에 따라」' },
      { examType: 'jlpt', level: 'N3', category: 'grammar',
        question: '「音楽を聞き___、勉強します」の（___）に入る言葉はどれですか。',
        options: ['ながら', 'てから', 'ために', 'ように'], answer: 0,
        explanation: '「〜ながら = 〜하면서」는 두 동작의 동시 진행을 나타냅니다.' },
      { examType: 'jlpt', level: 'N3', category: 'vocabulary',
        question: '「状況」の意味はどれですか。',
        options: ['방법', '목적', '상황', '판단'], answer: 2,
        explanation: '「状況（じょうきょう）」는 「상황」을 뜻합니다.' },
      { examType: 'jlpt', level: 'N3', category: 'grammar',
        question: '「健康のためなら、どんなことで___します」の（___）に入る言葉はどれですか。',
        options: ['さえ', 'も', 'だけ', 'ばかり'], answer: 0,
        explanation: '「〜でさえ = 〜조차, 〜라도」는 극단적인 예를 나타냅니다.' },
      { examType: 'jlpt', level: 'N3', category: 'grammar',
        question: '「彼女は美しい___、頭もいいです」の（___）に入る表現はどれですか。',
        options: ['だけでなく', 'ために', 'ながら', 'ように'], answer: 0,
        explanation: '「〜だけでなく = 〜뿐만 아니라」는 추가적인 정보를 나타냅니다.' },
      { examType: 'jlpt', level: 'N3', category: 'vocabulary',
        question: '「判断」의 의미는？',
        options: ['발표', '경험', '판단', '비교'], answer: 2,
        explanation: '「判断（はんだん）」는 「판단」을 뜻합니다.' },
      { examType: 'jlpt', level: 'N3', category: 'grammar',
        question: '「試験に合格した___、まだ不安が残ります」の（___）に入る言葉はどれですか。',
        options: ['ものの', 'から', 'ので', 'が'], answer: 0,
        explanation: '「〜ものの = 〜하긴 했지만」는 역접을 나타내며, 앞의 내용을 인정하면서 뒤에 부정적인 내용이 옵니다.' },
      { examType: 'jlpt', level: 'N3', category: 'vocabulary',
        question: '「比較」의 올바른 읽기는？',
        options: ['ひかく', 'ひかん', 'ひかつ', 'ひかく'], answer: 0,
        explanation: '「比較」는 「ひかく（hikaku）」로 읽으며 「비교」를 뜻합니다.' },
      { examType: 'jlpt', level: 'N3', category: 'grammar',
        question: '「諦めよう___、もう少し頑張ることにしました」の（___）に入る言葉はどれですか。',
        options: ['としたが', 'としても', 'としては', 'としたり'], answer: 0,
        explanation: '「〜ようとしたが = 〜하려고 했지만」는 의지의 시도 후 실제 다른 행동이 이어짐을 나타냅니다.' },

      // ═══════════════════════════════════════════
      // JLPT N2 — 10문제
      // ═══════════════════════════════════════════
      { examType: 'jlpt', level: 'N2', category: 'grammar',
        question: '「費用が高くても、やら___を得ない」の（___）に入る言葉はどれですか。',
        options: ['ない', 'ざる', 'なけれ', 'なく'], answer: 1,
        explanation: '「〜ざるを得ない = 〜하지 않을 수 없다, 부득이하다」는 부정 의미의 강조 표현입니다.' },
      { examType: 'jlpt', level: 'N2', category: 'grammar',
        question: '「環境問題___議論が続いています」の（___）に入る言葉はどれですか。',
        options: ['をめぐって', 'によって', 'にとって', 'について'], answer: 0,
        explanation: '「〜をめぐって = 〜을 둘러싸고」는 특정 주제를 중심으로 한 논의·다툼을 나타냅니다.' },
      { examType: 'jlpt', level: 'N2', category: 'grammar',
        question: '「試験に___、十分な準備が必要です」の（___）に入る言葉はどれですか。',
        options: ['際して', 'ついて', 'よって', 'おいて'], answer: 0,
        explanation: '「〜に際して = 〜에 즈음하여」는 특정 시점을 나타내는 격식체 표현입니다.' },
      { examType: 'jlpt', level: 'N2', category: 'vocabulary',
        question: '「把握」의 의미는？',
        options: ['비판', '파악', '실시', '개념'], answer: 1,
        explanation: '「把握（はあく）」는 「파악」을 뜻합니다. 「状況を把握する = 상황을 파악하다」' },
      { examType: 'jlpt', level: 'N2', category: 'grammar',
        question: '「食べる___食べるほど、おいしさがわかります」の（___）に入る言葉はどれですか。',
        options: ['ほど', 'でも', 'なら', 'ば'], answer: 3,
        explanation: '「〜ば〜ほど = 〜할수록」는 비례 관계를 나타냅니다. 「食べれば食べるほど = 먹을수록」' },
      { examType: 'jlpt', level: 'N2', category: 'grammar',
        question: '「費用___、時間もかかります」の（___）に入る言葉はどれですか。',
        options: ['はもとより', 'ともかく', 'はおろか', 'のみならず'], answer: 0,
        explanation: '「〜はもとより = 〜은 물론이고」는 당연한 전제에 추가 정보를 더할 때 사용합니다.' },
      { examType: 'jlpt', level: 'N2', category: 'vocabulary',
        question: '「傾向」의 올바른 읽기는？',
        options: ['けいこう', 'けいごう', 'けいこく', 'けいこん'], answer: 0,
        explanation: '「傾向」는 「けいこう（keikou）」로 읽으며 「경향」을 뜻합니다.' },
      { examType: 'jlpt', level: 'N2', category: 'grammar',
        question: '「環境保護に力を入れる___、経済も成長させています」の（___）に入る言葉はどれですか。',
        options: ['一方で', 'に対して', 'ためには', 'ことで'], answer: 0,
        explanation: '「〜一方で = 〜한편으로」는 두 가지 상반되거나 다른 사실을 나란히 제시합니다.' },
      { examType: 'jlpt', level: 'N2', category: 'grammar',
        question: '「彼は天才___、努力も怠りません」の（___）に入る言葉はどれですか。',
        options: ['であるからには', 'であるにすぎない', 'であるにもかかわらず', 'であるからこそ'], answer: 3,
        explanation: '「〜からこそ = 〜이기 때문에 더욱」는 긍정적인 이유·강조를 나타냅니다.' },
      { examType: 'jlpt', level: 'N2', category: 'vocabulary',
        question: '「前提」의 의미는？',
        options: ['철저', '타협', '전제', '경향'], answer: 2,
        explanation: '「前提（ぜんてい）」는 「전제」를 뜻합니다. 「前提条件 = 전제 조건」' },

      // ═══════════════════════════════════════════
      // JLPT N1 — 10문제
      // ═══════════════════════════════════════════
      { examType: 'jlpt', level: 'N1', category: 'grammar',
        question: '「この制度は来年度___廃止される予定です」の（___）に入る言葉はどれですか。',
        options: ['をもって', 'によって', 'にとって', 'において'], answer: 0,
        explanation: '「〜をもって = 〜을 기해, 〜로써」는 기준 시점이나 수단을 나타내는 격식체 표현입니다.' },
      { examType: 'jlpt', level: 'N1', category: 'grammar',
        question: '「彼の行動は親切心___ほかならない」の（___）に入る言葉はどれですか。',
        options: ['に', 'から', 'で', 'を'], answer: 0,
        explanation: '「〜にほかならない = 〜에 다름 아니다, 바로 〜이다」는 단정적 강조 표현입니다.' },
      { examType: 'jlpt', level: 'N1', category: 'grammar',
        question: '「そんな不正を見れば、誰でも怒ら___おかない」の（___）に入る言葉はどれですか。',
        options: ['ないでは', 'ずには', 'ないことには', 'ないとは'], answer: 0,
        explanation: '「〜ないではおかない = 반드시 〜하게 만든다」는 강한 결과·충동을 나타냅니다.' },
      { examType: 'jlpt', level: 'N1', category: 'vocabulary',
        question: '「忖度」의 의미는？',
        options: ['역설', '눈치보기·배려', '결함', '활달함'], answer: 1,
        explanation: '「忖度（そんたく）」는 「상대방의 마음을 헤아려 행동하는 것, 눈치 보기」를 뜻합니다.' },
      { examType: 'jlpt', level: 'N1', category: 'grammar',
        question: '「命___とあれば、何でもします」の（___）に入る言葉はどれですか。',
        options: ['のこと', 'のため', 'に関わる', 'に比べ'], answer: 2,
        explanation: '「命に関わる = 생명에 관계되는」이 「とあれば」와 결합해 극단적인 조건을 나타냅니다.' },
      { examType: 'jlpt', level: 'N1', category: 'grammar',
        question: '「プロジェクトの変更を余儀なく___」の（___）に入る言葉はどれですか。',
        options: ['させられた', 'された', 'させた', 'させて'], answer: 0,
        explanation: '「余儀なくさせられる = 부득이하게 〜하게 당하다」는 수동형 피사동을 사용합니다.' },
      { examType: 'jlpt', level: 'N1', category: 'vocabulary',
        question: '「脆弱」의 올바른 읽기는？',
        options: ['きじゃく', 'ぜいじゃく', 'もろじゃく', 'ぜいじゃく'], answer: 1,
        explanation: '「脆弱」는 「ぜいじゃく（zeijaku）」로 읽으며 「취약하다」를 뜻합니다.' },
      { examType: 'jlpt', level: 'N1', category: 'grammar',
        question: '「彼の功績を称え___やまない」の（___）に入る言葉はどれですか。',
        options: ['て', 'ても', 'ては', 'てこそ'], answer: 0,
        explanation: '「〜てやまない = 마음속 깊이 〜하다」는 감정의 지속·강조를 나타냅니다.' },
      { examType: 'jlpt', level: 'N1', category: 'grammar',
        question: '「結果の___いかんにかかわらず、最善を尽くします」の（___）に入る言葉はどれですか。',
        options: ['いかん', '如何', 'ゆえ', '次第'], answer: 0,
        explanation: '「結果のいかんにかかわらず = 결과가 어떻든 상관없이」는 조건에 관계없음을 나타냅니다.' },
      { examType: 'jlpt', level: 'N1', category: 'vocabulary',
        question: '「醸成」의 의미는？',
        options: ['파악', '비판', '조성(분위기를 만들다)', '부감'], answer: 2,
        explanation: '「醸成（じょうせい）」는 원래 술을 빚다는 뜻에서, 「분위기나 관계를 조성하다」의 의미로 사용됩니다.' },

      // ═══════════════════════════════════════════
      // TOEIC 200 — 10문제 (입문)
      // ═══════════════════════════════════════════
      { examType: 'toeic', level: 'toeic-200', category: 'grammar',
        question: 'She ___ to the office every day.',
        options: ['go', 'goes', 'going', 'gone'], answer: 1,
        explanation: '3인칭 단수 주어(She)에는 동사에 -s를 붙입니다. 「goes」가 올바른 현재형입니다.' },
      { examType: 'toeic', level: 'toeic-200', category: 'grammar',
        question: 'Please ___ your name on this form.',
        options: ['writes', 'wrote', 'write', 'writing'], answer: 2,
        explanation: '명령문은 동사 원형으로 시작합니다. 「write」가 올바른 형태입니다.' },
      { examType: 'toeic', level: 'toeic-200', category: 'vocabulary',
        question: 'What does "customer" mean?',
        options: ['직원', '관리자', '고객', '공급업체'], answer: 2,
        explanation: '「customer」는 「고객」을 뜻합니다. 제품이나 서비스를 구매하는 사람입니다.' },
      { examType: 'toeic', level: 'toeic-200', category: 'grammar',
        question: 'The office ___ on the third floor.',
        options: ['am', 'are', 'is', 'be'], answer: 2,
        explanation: '단수 주어(The office)에는 be동사 「is」를 사용합니다.' },
      { examType: 'toeic', level: 'toeic-200', category: 'vocabulary',
        question: 'What does "schedule" mean?',
        options: ['예산', '일정', '팀', '보고서'], answer: 1,
        explanation: '「schedule」는 「일정」을 뜻합니다. 「work schedule = 업무 일정」' },
      { examType: 'toeic', level: 'toeic-200', category: 'grammar',
        question: 'I ___ a report yesterday.',
        options: ['write', 'writes', 'written', 'wrote'], answer: 3,
        explanation: '「yesterday」가 있으므로 과거형을 씁니다. write의 과거형은 「wrote」입니다.' },
      { examType: 'toeic', level: 'toeic-200', category: 'grammar',
        question: 'This is ___ computer.',
        options: ['I', 'me', 'my', 'mine'], answer: 2,
        explanation: '명사 앞에 오는 소유격은 「my」입니다. 「my computer = 나의 컴퓨터」' },
      { examType: 'toeic', level: 'toeic-200', category: 'vocabulary',
        question: 'What does "budget" mean?',
        options: ['계약', '예산', '보고서', '회의'], answer: 1,
        explanation: '「budget」는 「예산」을 뜻합니다. 「annual budget = 연간 예산」' },
      { examType: 'toeic', level: 'toeic-200', category: 'grammar',
        question: '___ does she work? — She works in Seoul.',
        options: ['What', 'Where', 'When', 'Who'], answer: 1,
        explanation: '장소를 묻는 의문사는 「Where」입니다. 「Where do you work? = 어디서 일하세요?」' },
      { examType: 'toeic', level: 'toeic-200', category: 'grammar',
        question: 'We ___ have a meeting tomorrow.',
        options: ['wills', 'willing', 'will', 'willed'], answer: 2,
        explanation: '미래를 나타낼 때는 조동사 「will」 + 동사 원형을 사용합니다.' },

      // ═══════════════════════════════════════════
      // TOEIC 400 — 10문제 (초급)
      // ═══════════════════════════════════════════
      { examType: 'toeic', level: 'toeic-400', category: 'grammar',
        question: 'The report ___ by 5 PM yesterday.',
        options: ['submits', 'submitted', 'was submitted', 'is submitted'], answer: 2,
        explanation: '수동태(passive voice) + 과거: 「was submitted」. 「보고서가 제출됐다」는 의미입니다.' },
      { examType: 'toeic', level: 'toeic-400', category: 'vocabulary',
        question: 'What does "invoice" mean?',
        options: ['재고', '계약서', '청구서', '배송'], answer: 2,
        explanation: '「invoice」는 「청구서」를 뜻합니다. 거래 후 대금을 청구하는 문서입니다.' },
      { examType: 'toeic', level: 'toeic-400', category: 'grammar',
        question: 'The conference will be held ___ June 15.',
        options: ['in', 'on', 'at', 'by'], answer: 1,
        explanation: '날짜 앞에는 전치사 「on」을 씁니다. 「on June 15 = 6월 15일에」' },
      { examType: 'toeic', level: 'toeic-400', category: 'vocabulary',
        question: 'What does "revenue" mean?',
        options: ['비용', '수익/매출', '재고', '계약'], answer: 1,
        explanation: '「revenue」는 「수익, 매출」을 뜻합니다. 「annual revenue = 연간 매출」' },
      { examType: 'toeic', level: 'toeic-400', category: 'grammar',
        question: 'She has worked at this company ___ 2018.',
        options: ['since', 'for', 'from', 'during'], answer: 0,
        explanation: '특정 시점부터 현재까지는 「since」를 씁니다. 「since 2018 = 2018년부터」' },
      { examType: 'toeic', level: 'toeic-400', category: 'vocabulary',
        question: 'What does "department" mean?',
        options: ['본사', '계약', '부서', '승진'], answer: 2,
        explanation: '「department」는 「부서」를 뜻합니다. 「sales department = 영업 부서」' },
      { examType: 'toeic', level: 'toeic-400', category: 'grammar',
        question: 'This product is ___ expensive than the other one.',
        options: ['much more', 'many more', 'most', 'more'], answer: 3,
        explanation: '두 가지를 비교할 때 비교급 「more + 형용사」를 씁니다. 단, 단음절 형용사는 -er. 여기서는 「more expensive」' },
      { examType: 'toeic', level: 'toeic-400', category: 'vocabulary',
        question: 'What does "shipment" mean?',
        options: ['청구서', '배송', '재고', '부서'], answer: 1,
        explanation: '「shipment」는 「배송, 선적(물건을 보내는 것)」을 뜻합니다.' },
      { examType: 'toeic', level: 'toeic-400', category: 'grammar',
        question: '___ it was raining, we continued the outdoor event.',
        options: ['Because', 'Although', 'Since', 'So'], answer: 1,
        explanation: '역접(~임에도 불구하고)을 나타낼 때는 「although」를 씁니다.' },
      { examType: 'toeic', level: 'toeic-400', category: 'vocabulary',
        question: 'What does "complaint" mean?',
        options: ['홍보', '불만', '승진', '계약'], answer: 1,
        explanation: '「complaint」는 「불만, 불평, 민원」을 뜻합니다. 「file a complaint = 민원을 제기하다」' },

      // ═══════════════════════════════════════════
      // TOEIC 600 — 10문제 (중급)
      // ═══════════════════════════════════════════
      { examType: 'toeic', level: 'toeic-600', category: 'grammar',
        question: 'The project ___ by the time the client arrived.',
        options: ['completed', 'was completing', 'had been completed', 'has completed'], answer: 2,
        explanation: '과거 특정 시점 이전에 완료된 동작은 과거완료(had been p.p.)를 씁니다.' },
      { examType: 'toeic', level: 'toeic-600', category: 'vocabulary',
        question: 'What does "allocate" mean?',
        options: ['협상하다', '달성하다', '배분하다', '구현하다'], answer: 2,
        explanation: '「allocate」는 「배분하다, 할당하다」를 뜻합니다. 「allocate resources = 자원을 배분하다」' },
      { examType: 'toeic', level: 'toeic-600', category: 'grammar',
        question: 'If the budget ___ approved, we will start immediately.',
        options: ['is', 'was', 'were', 'had been'], answer: 0,
        explanation: '가능성이 있는 조건절에는 현재형을 씁니다. (1형 가정법: If + 현재, will + 동사원형)' },
      { examType: 'toeic', level: 'toeic-600', category: 'vocabulary',
        question: 'What does "negotiate" mean?',
        options: ['배분하다', '협상하다', '달성하다', '감독하다'], answer: 1,
        explanation: '「negotiate」는 「협상하다」를 뜻합니다. 「negotiate a contract = 계약을 협상하다」' },
      { examType: 'toeic', level: 'toeic-600', category: 'grammar',
        question: 'The employee ___ won the award has 10 years of experience.',
        options: ['which', 'whose', 'who', 'whom'], answer: 2,
        explanation: '사람을 수식하는 주격 관계대명사는 「who」입니다.' },
      { examType: 'toeic', level: 'toeic-600', category: 'vocabulary',
        question: 'What does "sustainable" mean?',
        options: ['효율적인', '생산적인', '지속 가능한', '전략적인'], answer: 2,
        explanation: '「sustainable」은 「지속 가능한」을 뜻합니다. 「sustainable development = 지속 가능한 발전」' },
      { examType: 'toeic', level: 'toeic-600', category: 'grammar',
        question: 'She is considering ___ a new position.',
        options: ['accept', 'to accept', 'accepting', 'accepted'], answer: 2,
        explanation: '「consider」 뒤에는 동명사(-ing)가 옵니다. 「consider accepting = 수락하는 것을 고려하다」' },
      { examType: 'toeic', level: 'toeic-600', category: 'vocabulary',
        question: 'What does "implement" mean?',
        options: ['평가하다', '배분하다', '실행하다', '협력하다'], answer: 2,
        explanation: '「implement」는 「실행하다, 시행하다」를 뜻합니다. 「implement a policy = 정책을 시행하다」' },
      { examType: 'toeic', level: 'toeic-600', category: 'grammar',
        question: 'You should ___ the contract before signing it.',
        options: ['review', 'reviewed', 'reviewing', 'to review'], answer: 0,
        explanation: '조동사(should) 뒤에는 동사 원형이 옵니다. 「should review = 검토해야 한다」' },
      { examType: 'toeic', level: 'toeic-600', category: 'vocabulary',
        question: 'What does "collaborate" mean?',
        options: ['감독하다', '협력하다', '평가하다', '달성하다'], answer: 1,
        explanation: '「collaborate」는 「협력하다, 공동 작업하다」를 뜻합니다.' },

      // ═══════════════════════════════════════════
      // TOEIC 800 — 10문제 (상급)
      // ═══════════════════════════════════════════
      { examType: 'toeic', level: 'toeic-800', category: 'grammar',
        question: 'The committee recommended that the proposal ___ approved.',
        options: ['is', 'was', 'be', 'were'], answer: 2,
        explanation: '주장·제안·권고 동사(recommend) 뒤 that절에는 원형 가정법(subjunctive: be)이 옵니다.' },
      { examType: 'toeic', level: 'toeic-800', category: 'vocabulary',
        question: 'What does "expedite" mean?',
        options: ['신속히 처리하다', '조달하다', '중재하다', '규정하다'], answer: 0,
        explanation: '「expedite」는 「신속히 처리하다, 앞당기다」를 뜻합니다. 「expedite delivery = 배송을 앞당기다」' },
      { examType: 'toeic', level: 'toeic-800', category: 'grammar',
        question: 'The system is believed ___ the data error.',
        options: ['to cause', 'to have caused', 'causing', 'to be caused'], answer: 1,
        explanation: '수동태 「is believed to have + p.p.」는 「과거에 〜했다고 믿어진다」는 의미입니다.' },
      { examType: 'toeic', level: 'toeic-800', category: 'vocabulary',
        question: 'What does "contingency plan" mean?',
        options: ['마케팅 계획', '비상 계획', '예산 계획', '연간 계획'], answer: 1,
        explanation: '「contingency plan」은 「비상(만일의) 계획」입니다. 예상치 못한 상황에 대비한 계획입니다.' },
      { examType: 'toeic', level: 'toeic-800', category: 'grammar',
        question: 'Not only did he finish the task, ___ also helped others.',
        options: ['he', 'but he', 'but also', 'and'], answer: 1,
        explanation: '「Not only A but also B」 구조에서 도치가 일어날 때 「not only did + S + V, but S + also + V」 형태가 됩니다.' },
      { examType: 'toeic', level: 'toeic-800', category: 'vocabulary',
        question: 'What does "stipulate" mean?',
        options: ['활용하다', '신속히 처리하다', '규정하다', '환급하다'], answer: 2,
        explanation: '「stipulate」는 「규정하다, 조건으로 명시하다」를 뜻합니다. 주로 계약·법률 문서에서 사용합니다.' },
      { examType: 'toeic', level: 'toeic-800', category: 'grammar',
        question: 'The manager insisted that all employees ___ the training.',
        options: ['attend', 'attends', 'attended', 'attending'], answer: 0,
        explanation: '주장·요구 동사(insist) 뒤 that절에 원형 가정법(attend)이 옵니다.' },
      { examType: 'toeic', level: 'toeic-800', category: 'vocabulary',
        question: 'What does "compliance" mean?',
        options: ['조달', '준수', '중재', '파악'], answer: 1,
        explanation: '「compliance」는 「준수, 법규 준수」를 뜻합니다. 「regulatory compliance = 규정 준수」' },
      { examType: 'toeic', level: 'toeic-800', category: 'grammar',
        question: '___ the project been properly managed, the losses could have been avoided.',
        options: ['If', 'Had', 'Should', 'Were'], answer: 1,
        explanation: '3형 가정법 도치: 「Had + S + p.p.」는 「If + S + had + p.p.」와 동일한 의미입니다.' },
      { examType: 'toeic', level: 'toeic-800', category: 'vocabulary',
        question: 'What does "leverage" mean in a business context?',
        options: ['위험을 피하다', '자원을 활용하다', '비용을 절감하다', '팀을 감독하다'], answer: 1,
        explanation: '비즈니스에서 「leverage」는 「자원·장점을 최대한 활용하다」를 뜻합니다.' },

      // ═══════════════════════════════════════════
      // TOEIC 900 — 10문제 (최고급)
      // ═══════════════════════════════════════════
      { examType: 'toeic', level: 'toeic-900', category: 'vocabulary',
        question: 'What does "circumvent" mean?',
        options: ['준수하다', '조성하다', '우회하다', '촉발하다'], answer: 2,
        explanation: '「circumvent」는 「우회하다, 교묘히 피하다」를 뜻합니다. 「circumvent regulations = 규정을 우회하다」' },
      { examType: 'toeic', level: 'toeic-900', category: 'grammar',
        question: 'No sooner ___ the meeting ended than the CEO left the room.',
        options: ['had', 'did', 'was', 'were'], answer: 0,
        explanation: '「No sooner had + S + p.p. + than」은 「〜하자마자」를 나타내는 도치 구문입니다.' },
      { examType: 'toeic', level: 'toeic-900', category: 'vocabulary',
        question: 'What does "commensurate" mean?',
        options: ['취약한', '성급한', '두드러진', '상응하는'], answer: 3,
        explanation: '「commensurate」는 「상응하는, 비례하는」을 뜻합니다. 「salary commensurate with experience = 경력에 상응하는 급여」' },
      { examType: 'toeic', level: 'toeic-900', category: 'vocabulary',
        question: 'What does "ameliorate" mean?',
        options: ['악화시키다', '개선하다', '촉발하다', '우회하다'], answer: 1,
        explanation: '「ameliorate」는 「개선하다, 완화하다」를 뜻합니다. 「ameliorate the situation = 상황을 개선하다」' },
      { examType: 'toeic', level: 'toeic-900', category: 'grammar',
        question: 'Such ___ the quality of the product that customers placed repeat orders.',
        options: ['is', 'was', 'were', 'are'], answer: 1,
        explanation: '「Such was + 명사 + that...」 구문은 「너무나 〜해서 …했다」를 나타냅니다. 과거 사건이므로 「was」를 씁니다.' },
      { examType: 'toeic', level: 'toeic-900', category: 'vocabulary',
        question: 'What does "exacerbate" mean?',
        options: ['개선하다', '우회하다', '악화시키다', '명시하다'], answer: 2,
        explanation: '「exacerbate」는 「악화시키다」를 뜻합니다. 「exacerbate the problem = 문제를 악화시키다」' },
      { examType: 'toeic', level: 'toeic-900', category: 'vocabulary',
        question: 'What does "pursuant to" mean?',
        options: ['〜에 반하여', '〜에 따라', '〜에도 불구하고', '〜에 더하여'], answer: 1,
        explanation: '「pursuant to」는 격식체 표현으로 「〜에 따라, 〜에 의거하여」를 뜻합니다. 법률·계약 문서에서 자주 쓰입니다.' },
      { examType: 'toeic', level: 'toeic-900', category: 'grammar',
        question: 'The ___ the economy recovers, the more jobs will be created.',
        options: ['sooner', 'soon', 'most soon', 'soonest'], answer: 0,
        explanation: '「The + 비교급, the + 비교급」 구문: 「The sooner, the more = 빠를수록 더 많이」. 비교급 「sooner」가 올바릅니다.' },
      { examType: 'toeic', level: 'toeic-900', category: 'vocabulary',
        question: 'What does "salient" mean?',
        options: ['형식적인', '성급한', '두드러진', '명확한'], answer: 2,
        explanation: '「salient」는 「가장 중요한, 두드러진」을 뜻합니다. 「salient points = 주요 사항」' },
      { examType: 'toeic', level: 'toeic-900', category: 'vocabulary',
        question: 'What does "perfunctory" mean?',
        options: ['특권적인', '명확한', '형식적인', '지속 가능한'], answer: 2,
        explanation: '「perfunctory」는 「형식적인, 건성의」를 뜻합니다. 「a perfunctory reply = 건성 답변」' },
    ]

    await this.examQuestionRepo.save(questions)
    this.logger.log(`Seeded ${questions.length} exam questions`)
  }
}
